#!/bin/bash
#run ./fun
#函数不带参数，返回值为最后一条语句或者用return 来指定，return 返回为0-255

echo fun

add ()
{
    return $(($1+$2))
}

min ()
{
    return $(($1-$2))
}

#$?会时时更新来保存函数返回值
add 2 3
b=$?
echo $b

min 3 2
b=$?
echo $b
