#!/bin/bash
#if ... then...fi
#run ./if_test

#输入一个字母
read -p "Please input (y/n):" tmp

#if...then...fi
if [ "$tmp" = "y" ] ; then
    echo "y"
fi

if [ "$tmp" = "n" ] ; then
    echo "n"
fi

#if...then...elif...fi
if [ "$tmp" = "y" ] ; then
    echo "y"
elif [ "$tmp" = "n" ] ; then
    echo "n"
fi

var=""

if [ -n "$var" ] ; then
    echo "var is $var"
else
    echo "var is tmp"
fi

if [ -f "$PWD/if_test" ] ; then
    echo "if file"
else
    echo "no file"
fi
